# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zoodroom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zoodroom.proto',
  package='zoodroom',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ezoodroom.proto\x12\x08zoodroom\"\x85\x01\n&ResourceOwnerPasswordCredentialRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\r\n\x05scope\x18\x05 \x01(\t\"\x99\x01\n\'ResourceOwnerPasswordCredentialResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_in\x18\x03 \x01(\x05\x12\r\n\x05scope\x18\x04 \x01(\t\x12\x1e\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x0f.zoodroom.Error\"\x8e\x01\n\x13\x43reateClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t\x12\x18\n\x10redirection_uris\x18\x03 \x03(\t\x12\x10\n\x08\x66ullname\x18\x04 \x01(\t\x12\x0c\n\x04logo\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\"G\n\x14\x43reateClientResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x08\x12\x1e\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0f.zoodroom.Error\"C\n\x18VerifyAccessTokenRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\";\n\x19VerifyAccessTokenResponse\x12\x1e\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x0f.zoodroom.Error\"7\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t2\xce\x02\n\x10\x43ranberryService\x12\x88\x01\n\x1fResourceOwnerPasswordCredential\x12\x30.zoodroom.ResourceOwnerPasswordCredentialRequest\x1a\x31.zoodroom.ResourceOwnerPasswordCredentialResponse\"\x00\x12O\n\x0c\x43reateClient\x12\x1d.zoodroom.CreateClientRequest\x1a\x1e.zoodroom.CreateClientResponse\"\x00\x12^\n\x11VerifyAccessToken\x12\".zoodroom.VerifyAccessTokenRequest\x1a#.zoodroom.VerifyAccessTokenResponse\"\x00\x62\x06proto3')
)




_RESOURCEOWNERPASSWORDCREDENTIALREQUEST = _descriptor.Descriptor(
  name='ResourceOwnerPasswordCredentialRequest',
  full_name='zoodroom.ResourceOwnerPasswordCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='zoodroom.ResourceOwnerPasswordCredentialRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_secret', full_name='zoodroom.ResourceOwnerPasswordCredentialRequest.client_secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='zoodroom.ResourceOwnerPasswordCredentialRequest.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='zoodroom.ResourceOwnerPasswordCredentialRequest.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope', full_name='zoodroom.ResourceOwnerPasswordCredentialRequest.scope', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=162,
)


_RESOURCEOWNERPASSWORDCREDENTIALRESPONSE = _descriptor.Descriptor(
  name='ResourceOwnerPasswordCredentialResponse',
  full_name='zoodroom.ResourceOwnerPasswordCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_token', full_name='zoodroom.ResourceOwnerPasswordCredentialResponse.access_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refresh_token', full_name='zoodroom.ResourceOwnerPasswordCredentialResponse.refresh_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expires_in', full_name='zoodroom.ResourceOwnerPasswordCredentialResponse.expires_in', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope', full_name='zoodroom.ResourceOwnerPasswordCredentialResponse.scope', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='zoodroom.ResourceOwnerPasswordCredentialResponse.error', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=318,
)


_CREATECLIENTREQUEST = _descriptor.Descriptor(
  name='CreateClientRequest',
  full_name='zoodroom.CreateClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='zoodroom.CreateClientRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_secret', full_name='zoodroom.CreateClientRequest.client_secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redirection_uris', full_name='zoodroom.CreateClientRequest.redirection_uris', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fullname', full_name='zoodroom.CreateClientRequest.fullname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logo', full_name='zoodroom.CreateClientRequest.logo', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='zoodroom.CreateClientRequest.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=463,
)


_CREATECLIENTRESPONSE = _descriptor.Descriptor(
  name='CreateClientResponse',
  full_name='zoodroom.CreateClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='created', full_name='zoodroom.CreateClientResponse.created', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='zoodroom.CreateClientResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=536,
)


_VERIFYACCESSTOKENREQUEST = _descriptor.Descriptor(
  name='VerifyAccessTokenRequest',
  full_name='zoodroom.VerifyAccessTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='zoodroom.VerifyAccessTokenRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='access_token', full_name='zoodroom.VerifyAccessTokenRequest.access_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=605,
)


_VERIFYACCESSTOKENRESPONSE = _descriptor.Descriptor(
  name='VerifyAccessTokenResponse',
  full_name='zoodroom.VerifyAccessTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='zoodroom.VerifyAccessTokenResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=666,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='zoodroom.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='zoodroom.Error.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='zoodroom.Error.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='zoodroom.Error.details', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=723,
)

_RESOURCEOWNERPASSWORDCREDENTIALRESPONSE.fields_by_name['error'].message_type = _ERROR
_CREATECLIENTRESPONSE.fields_by_name['error'].message_type = _ERROR
_VERIFYACCESSTOKENRESPONSE.fields_by_name['error'].message_type = _ERROR
DESCRIPTOR.message_types_by_name['ResourceOwnerPasswordCredentialRequest'] = _RESOURCEOWNERPASSWORDCREDENTIALREQUEST
DESCRIPTOR.message_types_by_name['ResourceOwnerPasswordCredentialResponse'] = _RESOURCEOWNERPASSWORDCREDENTIALRESPONSE
DESCRIPTOR.message_types_by_name['CreateClientRequest'] = _CREATECLIENTREQUEST
DESCRIPTOR.message_types_by_name['CreateClientResponse'] = _CREATECLIENTRESPONSE
DESCRIPTOR.message_types_by_name['VerifyAccessTokenRequest'] = _VERIFYACCESSTOKENREQUEST
DESCRIPTOR.message_types_by_name['VerifyAccessTokenResponse'] = _VERIFYACCESSTOKENRESPONSE
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResourceOwnerPasswordCredentialRequest = _reflection.GeneratedProtocolMessageType('ResourceOwnerPasswordCredentialRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEOWNERPASSWORDCREDENTIALREQUEST,
  __module__ = 'zoodroom_pb2'
  # @@protoc_insertion_point(class_scope:zoodroom.ResourceOwnerPasswordCredentialRequest)
  ))
_sym_db.RegisterMessage(ResourceOwnerPasswordCredentialRequest)

ResourceOwnerPasswordCredentialResponse = _reflection.GeneratedProtocolMessageType('ResourceOwnerPasswordCredentialResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEOWNERPASSWORDCREDENTIALRESPONSE,
  __module__ = 'zoodroom_pb2'
  # @@protoc_insertion_point(class_scope:zoodroom.ResourceOwnerPasswordCredentialResponse)
  ))
_sym_db.RegisterMessage(ResourceOwnerPasswordCredentialResponse)

CreateClientRequest = _reflection.GeneratedProtocolMessageType('CreateClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATECLIENTREQUEST,
  __module__ = 'zoodroom_pb2'
  # @@protoc_insertion_point(class_scope:zoodroom.CreateClientRequest)
  ))
_sym_db.RegisterMessage(CreateClientRequest)

CreateClientResponse = _reflection.GeneratedProtocolMessageType('CreateClientResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATECLIENTRESPONSE,
  __module__ = 'zoodroom_pb2'
  # @@protoc_insertion_point(class_scope:zoodroom.CreateClientResponse)
  ))
_sym_db.RegisterMessage(CreateClientResponse)

VerifyAccessTokenRequest = _reflection.GeneratedProtocolMessageType('VerifyAccessTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYACCESSTOKENREQUEST,
  __module__ = 'zoodroom_pb2'
  # @@protoc_insertion_point(class_scope:zoodroom.VerifyAccessTokenRequest)
  ))
_sym_db.RegisterMessage(VerifyAccessTokenRequest)

VerifyAccessTokenResponse = _reflection.GeneratedProtocolMessageType('VerifyAccessTokenResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYACCESSTOKENRESPONSE,
  __module__ = 'zoodroom_pb2'
  # @@protoc_insertion_point(class_scope:zoodroom.VerifyAccessTokenResponse)
  ))
_sym_db.RegisterMessage(VerifyAccessTokenResponse)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'zoodroom_pb2'
  # @@protoc_insertion_point(class_scope:zoodroom.Error)
  ))
_sym_db.RegisterMessage(Error)



_CRANBERRYSERVICE = _descriptor.ServiceDescriptor(
  name='CranberryService',
  full_name='zoodroom.CranberryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=726,
  serialized_end=1060,
  methods=[
  _descriptor.MethodDescriptor(
    name='ResourceOwnerPasswordCredential',
    full_name='zoodroom.CranberryService.ResourceOwnerPasswordCredential',
    index=0,
    containing_service=None,
    input_type=_RESOURCEOWNERPASSWORDCREDENTIALREQUEST,
    output_type=_RESOURCEOWNERPASSWORDCREDENTIALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateClient',
    full_name='zoodroom.CranberryService.CreateClient',
    index=1,
    containing_service=None,
    input_type=_CREATECLIENTREQUEST,
    output_type=_CREATECLIENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VerifyAccessToken',
    full_name='zoodroom.CranberryService.VerifyAccessToken',
    index=2,
    containing_service=None,
    input_type=_VERIFYACCESSTOKENREQUEST,
    output_type=_VERIFYACCESSTOKENRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRANBERRYSERVICE)

DESCRIPTOR.services_by_name['CranberryService'] = _CRANBERRYSERVICE

# @@protoc_insertion_point(module_scope)
